### ISSUE TITLE
DataError beim Versuch zu fitten

### ISSUE THREAD

**Issue by kawindme** [ahaselsteiner/viroconweb#1]
`1yeardata_vanem2012pdf.csv` aus dem testfiles folder hochgeladen. Direkt danach auf `fit` geklickt. Als Namen `"waveheight"` eingegeben, 15 Stufen und Weibull als Verteilung. (Was mich etwas gewundert hat war, dass obwohl die csv eigentlich 2 Kanäle enthält ich nur eine Verteilung zum fitten auswählen konnte.)
Fehlermeldung ist in 
[DataError at _enviro_measurefiles_7_fit.zip](https://github.com/ahaselsteiner/virocon/files/1423330/DataError.at._enviro_measurefiles_7_fit.zip)
zu finden.

**Comment by ahaselsteiner** [comment]
As discussed: The file structure of the .csv should be checked. If it is not as specified an error message should be returned to the user.

**Comment by ahaselsteiner** [comment]
@kawindme Kai, since I think you are working on this issue, please assign it to yourself.

**Comment by ahaselsteiner** [comment]
Done by Kai.
