### ISSUE TITLE
Prevent ViroCon from timing out when performing a fit

### ISSUE THREAD

**Issue by ahaselsteiner** [ahaselsteiner/viroconweb#138]
**I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] code improvement request

## Expected behavior
**How should it work (with the bug fixed or the feature implemented)?**
If ViroCon starts a fitting computation it should finish it.

**Screenshot**

## Actual behavior
**How does it currently work (with the bug causing problems or without the feature)?**
ViroCon started fitting (Vanem2012 model with standard test data set) and stopped after 30 seconds since this is Heroku's time for a timeout. Interestingly, the fitting was done, but probably not all plots have been plotted in time because an Django object of the probabilistic model was created and when we inspected it only the first intervals of the plots were present.

**Screenshot**
![image](https://user-images.githubusercontent.com/11452055/39255709-76597ac6-48ad-11e8-9de8-0b69934558df.png)

## Steps to reproduce the problem (how to see the actual behavior)

  1. Upload standard .csv file to Heroku app
  2. Fit Vanem2012 model
  3. See if it times out

**Comment by ahaselsteiner** [comment]
We just tried to reproduce the bug. This time we did not have a timeout.

**Comment by janlehmk** [comment]
Look at https://github.com/ahaselsteiner/viroconweb/issues/145

**Comment by ahaselsteiner** [comment]
Done by Jannnik and myself.
