### ISSUE TITLE
Computing a contour can cause a timeout

### ISSUE THREAD

**Issue by ahaselsteiner** [ahaselsteiner/viroconweb#145]
**I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] code improvement request

## Expected behavior
**How should it work (with the bug fixed or the feature implemented)?**
Users should not be allowed to perform calculations which cause a time out. In case a timeout occurs the user should be preseneted with an appropriate error message.

**Screenshot**

## Actual behavior
**How does it currently work (with the bug causing problems or without the feature)?**
Timeouts can occur and the user does get the information "application error".

**Screenshot**
Probabilistic model:
![image](https://user-images.githubusercontent.com/11452055/39259467-c532fa74-48b6-11e8-9327-1da00ac1538a.png)

HDC setting:
![image](https://user-images.githubusercontent.com/11452055/39259440-b382de02-48b6-11e8-9b91-3b28935e58b0.png)

Error:
![image](https://user-images.githubusercontent.com/11452055/39259415-a3bc50b6-48b6-11e8-97b2-099a4a07ef7b.png)

## Steps to reproduce the problem (how to see the actual behavior)

  1. Define the given probabilistic model (see screenshot)
  2. Calculate a HDC on heroku (see screenshot)
  3. Get the error

**Comment by ahaselsteiner** [comment]
I will write a function, which roughly approximates the required computing time to calculate an environmental contour. If it would be too long, the user is not allowed to perform the calculation if RUN_MODE is online-dev or production (in local-dev there is no limit).

A similar approach should be applied to too much computing time required for fitting, see #138

**Comment by ahaselsteiner** [comment]
@janlehmk As discussed your idea of using the multiprocessing timeout method sounds great. Go ahead and try to implementing it.

Consequently, I will not write the function, which approximates computing time.

**Comment by ahaselsteiner** [comment]
I am implementing a function so estimate the required computing time nevertheless. In case the timeout method works we do not need to use it.

**Comment by janlehmk** [comment]
@kawindme 
@ahaselsteiner 
I created a pull request in the Viroconcom repository for this issue. The timeout can be defined as parameter by creating a Fit/Contour -object. The default value for this parameter is '1e6' the highest possible value on Windows systems.

https://github.com/ahaselsteiner/viroconcom/pull/19

**Comment by ahaselsteiner** [comment]
@janlehmk Thanks. @kawindme had a look at it. Although he does not like the changes, which were necessary, too much, he does not have a better idea, so we go with this solution. I will implement to catch the TimeOutError you are reaising in viroconweb properly and will then merge your viroconcom pull request.

**Comment by ahaselsteiner** [comment]
Impemented for fit: 
![image](https://user-images.githubusercontent.com/11452055/39958723-3aae805e-5607-11e8-9dd7-fb31fd8e12ab.png)

And for the contour:
![image](https://user-images.githubusercontent.com/11452055/39958726-5470639a-5607-11e8-8fbc-3d800d1bca89.png)

**Comment by ahaselsteiner** [comment]
Done and merged into master.
