### ISSUE TITLE
Inconsistency in plot of fits

### ISSUE THREAD

**Issue by ahaselsteiner** [ahaselsteiner/viroconweb#158]
**I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] code improvement request

## Expected behavior
**How should it work (with the bug fixed or the feature implemented)?**
The mu value should be plotted correctly.

**Screenshot**

## Actual behavior
**How does it currently work (with the bug causing problems or without the feature)?**
Either in the plot of a basic fit or in a fit of fits the mu has a wrong value.
In the screenshot shown below the mu value for the interval 12<Hs<14 is 2.5 in the basic fit plot and about 12.5 in the fit of fit plot.

Only one value can be correct. 

Probably the fit of fit plot is incorrect and the problem is probably due to a problem with the mu conversion.

**Screenshot**
![image](https://user-images.githubusercontent.com/11452055/39702226-596877f4-5204-11e8-8879-89dda120694d.png)

## Steps to reproduce the problem (how to see the actual behavior)

  1. Fit the correct Vanem model to the Vanem data set
  2. Visually inspect the fit
  3. See the inconsistency

**Comment by ahaselsteiner** [comment]
@topape Since you are working on plotting: Can you take a look at this issue?

**Comment by topape** [comment]
I fixed it
<img width="772" alt="bildschirmfoto 2018-05-07 um 16 04 45" src="https://user-images.githubusercontent.com/34214376/39706295-3e47f9b0-5211-11e8-8c63-aceb42635406.png">
